#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use warnings;
use strict;
use JSON;
use esmith::ConfigDB;

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';

my $input = readInput();
my $cmd = $input->{'action'};

sub format_category
{
    my $name = shift;
    my $description = $name;
    $description =~ s/ET(-emerging)*(-)*//;
    $description =~ s/_/ /g;

    return { "name" => $name, "Description" => ucfirst($description) };
}

my $ret;

if ($cmd eq 'categories') {
    my @categories;
    my $out = `/usr/libexec/nethserver/suricata-list-categories`;
    foreach (@{safe_decode_json($out)}) {
        # skip non-ET categories
        next if ($_ !~ /^ET/);
        push(@categories, format_category($_));
    }
    $ret->{'categories'} = \@categories;
} elsif ($cmd eq 'configuration') {
    my (@alert, @block);
    my $db = esmith::ConfigDB->open_ro();
    $ret->{'status'} = $db->get_prop('suricata', 'status');
    foreach (split(",", $db->get_prop('suricata', 'AlertCategories'))) {
        push(@alert, format_category($_));
    }
    foreach (split(",", $db->get_prop('suricata', 'BlockCategories'))) {
        push(@block, format_category($_));
    }
    $ret->{'AlertCategories'} = \@alert;
    $ret->{'BlockCategories'} = \@block;
}
print encode_json($ret);
