#!/usr/bin/perl -w
#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);
use File::Path;

#--------------------------------------------------
# actions for nethserver-suricata-update event
#--------------------------------------------------

$event = "nethserver-suricata-update";
event_templates($event,
    '/etc/sysconfig/suricata',
    '/etc/suricata/suricata.yaml',
    '/etc/sudoers',
    '/etc/logrotate.d/suricata'
);

event_services($event, 'suricata' => 'restart');
event_actions($event, 'initialize-default-databases' => '00');


#--------------------------------------------------
# actions for nethserver-suricata-save event
#--------------------------------------------------

$event = "nethserver-suricata-save";
event_templates($event,
    '/etc/sysconfig/suricata',
    '/etc/suricata/suricata.yaml',
    '/etc/logrotate.d/suricata'
);

event_services($event, 'suricata' => 'restart');

#--------------------------------------------------
# actions for trusted-networks-modify event
#--------------------------------------------------

$event = "trusted-networks-modify";
event_templates($event,
    '/etc/suricata/suricata.yaml',
);

event_services($event, 'suricata' => 'restart');

