#!/usr/bin/php
<?php
/*
 * Copyright (C) 2020 Nethesis S.r.l.
 * http://www.nethesis.it - nethserver@nethesis.it
 *
 * This script is part of NethServer.
 *
 * NethServer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or any later version.
 *
 * NethServer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NethServer.  If not, see COPYING.
*/


require_once("/usr/libexec/nethserver/api/lib/Helpers.php");

$data = readInput();

$v = new LegacyValidator($data);
 if ($data['action'] == 'update-bypass' || $data['action'] == 'create-bypass') {
    $hdb = new EsmithDatabase('hosts');
    $fdb = new EsmithDatabase('ips');

    # search for existing bypass with the same Host
    if (($data['action'] == 'create-bypass' || $data['action'] == 'update-bypass') && $data['type'] == 'bypass') {
        foreach ($fdb->getAll('bypass') as $bypass) {
            # check if bypass is raw (like an IP) or not
            if (strpos($bypass['Host'], ';') !== false) {
                list($type, $name) = explode(";", $bypass['Host']);
            } else {
                $name = $bypass['Host'];
            }

            if ($data['Host']['name'] == $name) {
                $v->addValidationError('Host', 'bypass_already_exists');
            }
        }
    }

    $v->declareParameter('status', Validate::SERVICESTATUS);

    if (isset($data['Host']) && $data['Host'] && $data['Host']['type'] != 'raw') {
        if (!$hdb->getKey($data['Host']['name'])) {
            $v->addValidationError('Host', 'object_not_found');
        }
    }

    $ip_v = $v->createValidator(Validate::IPv4);
    $cidr_v = $v->createValidator(Validate::CIDR_BLOCK);
    $ip_cidr_v = $v->createValidator()->orValidator($ip_v, $cidr_v);
    if (isset($data['Host']) && $data['Host'] && $data['Host']['type'] == 'raw') {
        if (!$ip_cidr_v->evaluate($data['Host']['name'])) {
            $v->addValidationError('Host', 'valid_ip_or_cidr', $data['Host']);
        }
    }
    if ($data['action'] == 'update-bypass') {
        if (!$fdb->getKey($data['name'])) {
            $v->addValidationError('name', 'bypass_not_found');
        }
    } # else on creation name is auto-generated, no validation required
}

# Validate the input
if ($v->validate()) {
    success();
} else {
    error($v);
}
