#!/usr/bin/python

#
# Copyright (C) 2017 Nethesis S.r.l.
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import gettext
import json
import os
import sys

out = ''

try:
    status = os.popen('/sbin/e-smith/config getprop suricata status').read()
    blocked = os.popen('/sbin/e-smith/config getprop suricata BlockCategories').read()
    alert = os.popen('/sbin/e-smith/config getprop suricata AlertCategories').read()
except:
    pass

if(not status or status.strip() == 'disabled'):
    exit(0)

if(status.strip() == "enabled" and blocked.strip() == "" and alert.strip() == ""):
    gettext.install('nethserver-suricata')
    msg = {"action": {"label": _('Suricata IPS is not correctly configured'), "url": '/IPS'}, "text": _('Enable at least one rule category'), "icon": "warning"}
    json.dump(msg, sys.stdout)

